# Generated by Django 6.0.6 on 2026-06-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_24782002', '0002_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
