# Generated by Django 6.0.3 on 2026-05-20 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Judul')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('location', models.CharField(max_length=100, verbose_name='Lokasi')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REPORTED', 'Dilaporkan'), ('VERIFIED', 'Diverifikasi'), ('IN_PROGRESS', 'Diproses'), ('RESOLVED', 'Diselesaikan')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
